#pragma kernel Dither
#pragma kernel ClearError

#define GROUP_SIZE_X 16
#define GROUP_SIZE_Y 1
#define GROUP_SIZE_Z 1
#define GROUP_SIZE GROUP_SIZE_X * GROUP_SIZE_Y * GROUP_SIZE_Z

static const float4 DitherWeights = float4(7.0 / 16.0, 3.0 / 16.0, 5.0 / 16.0, 1.0 / 16.0);

Texture2D<float4> _Source;
RWTexture2D<float4> _Result;
Texture3D<float4> _ColorPalette;
RWTexture2D<float4> _ErrorValues;
RWStructuredBuffer<uint> _WorkgroupRider;
RWStructuredBuffer<uint> _WorkgroupProgress;

SamplerState sampler_PointClamp;

groupshared uint Progress[GROUP_SIZE];
groupshared uint WorkgroupNumber;

void FloydSteinberg(uint2 pixel, uint2 screenSize)
{
    float3 sourceColor = _Source.Load(int3((int2)pixel, 0)).rgb;
    float3 accumulatedError = _ErrorValues[pixel].rgb;
    float3 modifiedColor = sourceColor + accumulatedError;
    float3 paletteColor = _ColorPalette.SampleLevel(sampler_PointClamp, modifiedColor, 0).rgb;
    float3 error = modifiedColor - paletteColor;
    float4 originalError;

    _Result[pixel] = float4(paletteColor, 1.0);
    
    if (pixel.x < screenSize.x - 1)
    {
        _ErrorValues[pixel + uint2(1, 0)] += float4(error * DitherWeights.x, 0.0);
        _ErrorValues[pixel + uint2(1, 1)] += float4(error * DitherWeights.w, 0.0);
    }
    
    if (pixel.y < screenSize.y - 1)
    {
        _ErrorValues[pixel + uint2(0, 1)] += float4(error * DitherWeights.z, 0.0);
        
        if (pixel.x > 0)
            _ErrorValues[pixel + uint2(0, 1) - uint2(1, 0)] += float4(error * DitherWeights.y, 0.0);
    }
}

[numthreads(GROUP_SIZE_X, GROUP_SIZE_Y, GROUP_SIZE_Z)]
void Dither(uint3 id : SV_GroupThreadID)
{
    uint threadID = id.x;

    if (threadID == 0)
    {
        InterlockedAdd(_WorkgroupRider[0], 1, WorkgroupNumber);

        for (int i = 0; i < GROUP_SIZE_X; i++)
            Progress[i] = 0;
    }

    AllMemoryBarrierWithGroupSync();

    uint width;
    uint height;

    _Source.GetDimensions(width, height);

    uint2 screenSize = uint2(width, height);
    uint y = height - 1 - (WorkgroupNumber * GROUP_SIZE_X + threadID);
    
    for (uint x = 0; x < width;)
    {
        if (threadID > 0)
        {
            if (Progress[threadID - 1] >= min(x + 2, width))
            {
                FloydSteinberg(uint2(x, y), screenSize);
                x++;
            }
        }
        else if (WorkgroupNumber > 0)
        {
            if (_WorkgroupProgress[WorkgroupNumber - 1] >= min(x + 2, width))
            {
                FloydSteinberg(uint2(x, y), screenSize);
                x++;
            }
        }
        else
        {
            FloydSteinberg(uint2(x, y), screenSize);
            x++;
        }

        if (threadID == GROUP_SIZE_X - 1)
        {
            uint original;
            InterlockedExchange(_WorkgroupProgress[WorkgroupNumber], x, original);
        }
        else
            Progress[threadID] = x;
    }
}

[numthreads(1, 1, 1)]
void ClearError(uint3 id : SV_GroupThreadID)
{
    uint width;
    uint height;

    _Source.GetDimensions(width, height);
    
    for (uint y = 0; y < height; y++)
        for (uint x = 0; x < width; x++)
            _ErrorValues[uint2(x, y)] = float4(0, 0, 0, 0);
}